### ISSUE TITLE
Is this parser interoperable with socket.io-parser?

### ISSUE THREAD

**Issue by JamesMGreene** [darrachequesne/socket.io-json-parser#1]
Is this parser (socket.io-json-parser) interoperable with the default parser ([socket.io-parser](https://github.com/socketio/socket.io-parser)), assuming no binary data items (e.g. files, `Blob`s, etc.) are included in the messages? I can't find any mention of interoperability—or lack thereof—between the parsers in the documentation.

### My Use Case

I have existing systems deployed with the default parser because I did not notice that alternate, more optimized parsers existed. Now that I do, I would like to update my socket.io configuration to use the optimized JSON parser. However, as new deployments will need to continue to interoperate with older systems, I need to know if the JSON parser and the default parser can interoperate (again, assuming no binary data is involved).

---

_Related:_ https://github.com/socketio/socket.io-parser/issues/73

**Comment by darrachequesne** [comment]
No, the parsers are not compatible. Consequently, you'll also have to use the same parser on the client and the server, so they can understand each other.

**Comment by JamesMGreene** [comment]
Bummer but I feared as much. Thanks.
