### ISSUE TITLE
Parser is swallowing errors if an error occurs in the callback for an event

### ISSUE THREAD

**Issue by divillysausages** [darrachequesne/socket.io-json-parser#3]
Currently the `Decoder` method looks like this:

```
Decoder.prototype.add = function (obj) {
  try {
    var decoded = JSON.parse(obj);
    this.emit('decoded', decoded);
  } catch (e) {
    this.emit('decoded', errorPacket);
  }
};
```

If an error occurs in the `emit` callback (socket.io-client `Manager` listens for `decoded`, and emits `packet`, `Socket` listens for `packet` and calls `onpacket`, which eventually calls your listener) then the error is swallowed by the `catch`, as the `errorPacket` emitted instead doesn't contain the `nsp` property, meaning the `Socket` will ignore the message:

```
Socket.prototype.onpacket = function (packet) {
  if (packet.nsp !== this.nsp) return;
  ...
```

Ideally the `try..catch` should just encapsulate the `JSON.parse` call, no?

There are 2 solutions that I can see:

1. Move the `decoded` declaration outside of the `try..catch`, then if an error is thrown, we'll be able to access the `nsp` property of the decoded object (with a default of '/' if the error was the `JSON.parse` itself):

```
Decoder.prototype.add = function (obj) {
  var decoded = null;
  try {
    decoded = JSON.parse(obj);
    this.emit('decoded', decoded);
  } catch (e) {
    errorPacket.nsp = (decoded) ? decoded.nsp : '/';
    this.emit('decoded', errorPacket);
  }
};
```

The downside to this is that the `decoded` event gets emitted twice for the one event

2. Use the `try..catch` just for the `JSON.parse`, and let the client code handle any error resulting from the `emit()`. The downside to this is that if there is an error in `JSON.parse`, then we won't be able to get the `nsp`, so the `Socket` will ignore the error. That said, looking at the default socket.io parser, they seem to be returning the same object, so will have the same problem.

In that case, your method will look like:

```
Decoder.prototype.add = function (obj) {
  var decoded = null;
  try {
    decoded = JSON.parse(obj);
  } catch (e) {
    console.error( "Invalid JSON", e );
  }
  this.emit('decoded', (decoded) ? decoded : errorPacket);
};
```

It's possible that this is also what's happening in #2

**Comment by darrachequesne** [comment]
@divillysausages you are absolutely right, any parsing error should be caught higher in the stack ([here](https://github.com/socketio/socket.io/blob/2.3.0/lib/client.js#L194-L198) on the server-side).

I've updated the behavior of the default parser as well: https://github.com/socketio/socket.io-parser/commit/c327acbc3c3c2d0b2b439136cbcb56c81db173d6

Sorry for the delay!
